In [1]:
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from glob import glob
from pprint import pprint
import tensorflow as tf
from tensorflow import keras
import tensorflow_hub as hub
import os

In [2]:
LABEL_INT_DICT = np.unique(pd.read_csv('D:/data_ai/5_AI/ucf11_train_vid.csv')['label'])
pprint(LABEL_INT_DICT)
LABEL_STR_DICT = {k:v for v, k in enumerate(LABEL_INT_DICT)}    # KEY값과 VALUE값 바꿈
pprint(LABEL_STR_DICT)

array(['biking', 'diving', 'golf', 'juggle', 'jumping', 'riding',
       'shooting', 'spiking', 'swing', 'tennis', 'walk'], dtype=object)
{'biking': 0,
 'diving': 1,
 'golf': 2,
 'juggle': 3,
 'jumping': 4,
 'riding': 5,
 'shooting': 6,
 'spiking': 7,
 'swing': 8,
 'tennis': 9,
 'walk': 10}


In [3]:
model = keras.models.load_model(
    'D:/data_ai/5_AI/ucf11_weights/05-0.96.hdf5',
    custom_objects={'KerasLayer':hub.KerasLayer}
)

model.build([None, 256, 256, 3])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 1280)              5919312   
                                                                 
 dense (Dense)               (None, 11)                14091     
                                                                 
Total params: 5,933,403
Trainable params: 5,872,795
Non-trainable params: 60,608
_________________________________________________________________


In [4]:
csv_path = 'D:/data_ai/5_AI/ucf11_valid_vid.csv'
valid_df = pd.read_csv(csv_path)

idx = 21
elem = valid_df.iloc[idx]

cap = cv2.VideoCapture(
    elem['file_path']
)

fourcc = cv2.VideoWriter_fourcc(*'MJPG')
writer = cv2.VideoWriter('D:/data_ai/5_AI/movie.avi', fourcc, 30, (256, 256), True)

while True:
    ret, frame = cap.read()
    if not ret:
        break
        
    frame_ = frame.copy()
    frame_ = cv2.cvtColor(frame_, cv2.COLOR_BGR2RGB)
    frame_ = cv2.resize(frame_, (256, 256))
    frame_ = frame_.astype('float32')
    frame_ = frame_ / 255
    
    # np.newaxis : 1 차원 추가 => 리스트 하나 추가[[리스트],[원래 배열]] => 결국 1차원, ... : 그대로 파라미터 채워주는 것
    # 비교하기 위해
    pred = model.predict(frame_[np.newaxis, ...])    
    label = LABEL_INT_DICT[np.argmax(pred)]
    
    frame = cv2.resize(frame, (256, 256))
    cv2.putText(frame, label, (50, 45), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (0, 255, 0), 5)
    writer.write(frame)
    
cap.release()
writer.release()

# 예측 값이 튀면 결과 값이 변할 수 있음

1/1 [==============================] - 0s 84ms/step


1/1 [==============================] - 0s 72ms/step


In [6]:
cap = cv2.VideoCapture(
    elem['file_path']
)

fourcc = cv2.VideoWriter_fourcc(*'MJPG')
writer = cv2.VideoWriter('D:/data_ai/5_AI/roll.avi', fourcc, 30, (256, 256), True)

queue = []

while True:
    ret, frame = cap.read()
    if not ret:
        break
        
    frame_ = frame.copy()
    frame_ = cv2.cvtColor(frame_, cv2.COLOR_BGR2RGB)
    frame_ = cv2.resize(frame_, (256, 256))
    frame_ = frame_.astype('float32')
    frame_ = frame_ / 255
    
    print(frame_)
    print("*" * 30)
    # np.newaxis : 1 차원 추가 => 리스트 하나 추가[[리스트],[원래 배열]] => 결국 1차원, ... : 그대로 파라미터 채워주는 것
    # 비교하기 위해
    pred = model.predict(frame_[np.newaxis, ...])   
    print(pred)
    
    queue.append(pred)
    
    # 평균으로 하여 결과 값을 안정적으로 리턴
    results = np.array(queue).mean(axis=0)
    print("✔" * 30)
    print(results)
    print("✔" * 30)
    label = LABEL_INT_DICT[np.argmax(results)]
    
    frame = cv2.resize(frame, (256, 256))
    cv2.putText(frame, label, (50, 45), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (0, 255, 0), 5)
    writer.write(frame)
    
cap.release()
writer.release()

[[[0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 ...

 [[0.3529412  0.34509805 0.32941177]
  [0.3529412  0.34509805 0.32941177]
  [0.3529412  0.34509805 0.32941177]
  ...
  [0.30588236 0.29803923 0.28235295]
  [0.30588236 0.29803923 0.28235295]
  [0.30588236 0.29803923 0.28235295]]

 [[0.3529412  0.34509805 0.32941177]
  [0.3529412  0.34509805 0.32941177]


1/1 [==============================] - 0s 67ms/step
[[1.8871742e-06 1.0900598e-06 1.1608872e-06 1.3571655e-06 2.0168674e-05
  9.9996042e-01 1.0528302e-07 7.5752826e-07 2.7388498e-06 6.5969658e-07
  9.6259146e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[5.9711101e-06 2.1865892e-06 1.9064807e-06 3.3532415e-06 3.3783952e-05
  9.9991095e-01 3.1523584e-07 3.3617439e-06 4.2264246e-06 1.2036901e-06
  3.2720931e-05]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.9

1/1 [==============================] - 0s 72ms/step
[[1.16805466e-04 7.62718309e-06 6.14855389e-06 1.80977577e-06
  2.99636886e-04 9.99370396e-01 8.98775966e-07 3.27683392e-06
  1.91950639e-05 6.26384644e-06 1.67905455e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[6.5172542e-05 6.3030989e-06 4.5053675e-06 3.3374376e-06 1.7749198e-04
  9.9956447e-01 6.0823669e-07 3.3236288e-06 2.0268939e-05 3.4365992e-06
  1.5113616e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.5294118  0.58431375 0.6313726 ]
  [0.46666667 0.52156866 0.5686275 ]
  [0.41568628 0.46666667 0.5176471 ]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.45490196 0.5137255  0.56078434]
  [0.40392157 0.4627451  0.5058824 ]
  [0.3647059  0.41960785 0.46666667]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.42352942 0.47843137 0.5254902 ]
  [0.39607844 0.4509804  0.49803922]
  [0.3764706  0.4

1/1 [==============================] - 0s 81ms/step
[[1.1138477e-06 9.4029855e-07 4.8223285e-07 1.2208900e-06 5.0751601e-06
  9.9998391e-01 1.4801375e-07 9.7581824e-07 1.4823618e-06 6.7299703e-07
  3.9882752e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[4.5916615e-05 4.6320879e-06 3.2609953e-06 2.4770056e-06 1.2382781e-04
  9.9969679e-01 4.5596875e-07 2.4154288e-06 1.4731004e-05 2.6095629e-06
  1.0284736e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.9843137  1.         1.        ]
  [0.9843137  1.         1.        ]
  [0.9843137  1.         1.        ]
  ...
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]]

 [[0.9843137  1.         1.        ]
  [0.9843137  1.         1.        ]
  [0.9843137  1.         1.        ]
  ...
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]]

 [[0.9843137  1.         1.        ]
  [0.9843137  1.         1.        ]
  [0.9843137  1.         1. 

1/1 [==============================] - 0s 89ms/step
[[6.3351454e-06 2.3697353e-06 1.0626105e-06 1.8917101e-06 3.1513293e-05
  9.9993873e-01 2.8994992e-07 1.8334698e-06 7.0827359e-06 1.0986095e-06
  7.7922205e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.5201465e-05 3.9206598e-06 2.7173844e-06 2.2650722e-06 9.9116805e-05
  9.9975955e-01 4.0544555e-07 2.2769455e-06 1.2219777e-05 2.2256818e-06
  8.0023718e-05]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.9529412  0.95686275 0.96862745]
  [0.9529412  0.95686275 0.96862745]
  [0.9529412  0.95686275 0.96862745]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.95686275 0.9607843  0.972549  ]
  [0.95686275 0.9607843  0.972549  ]
  [0.95686275 0.9607843  0.972549  ]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.9529412  0.95686275 0.96862745]
  [0.9529412  0.95686275 0.96862745]
  [0.9529412  0.95686275 0.9

1/1 [==============================] - 0s 76ms/step
[[4.6763442e-05 6.0867578e-06 3.9515985e-06 1.4169706e-05 2.2461871e-04
  9.9905497e-01 1.4841349e-06 1.4219074e-05 4.3029711e-05 4.7236740e-06
  5.8613817e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.3608292e-05 4.3965083e-06 2.8823238e-06 3.2532384e-06 1.3782388e-04
  9.9969637e-01 4.9320755e-07 2.9428732e-06 1.4662710e-05 2.3002833e-06
  1.0128675e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.29411766 0.35686275 0.34901962]
  [0.30980393 0.37254903 0.3647059 ]
  [0.3372549  0.4        0.39215687]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.29411766 0.35686275 0.34901962]
  [0.30980393 0.37254903 0.3647059 ]
  [0.3372549  0.4        0.39215687]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.29411766 0.35686275 0.34901962]
  [0.30980393 0.37254903 0.3647059 ]
  [0.3372549  0.4        0.3

1/1 [==============================] - 0s 78ms/step
[[5.7963716e-05 4.6314290e-06 9.1706801e-07 7.2002979e-07 5.0595441e-05
  9.9987137e-01 2.5786920e-07 1.5033339e-06 6.5162744e-06 6.7090804e-07
  4.6815740e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[1.8055586e-03 6.8726578e-05 3.5188172e-05 1.1565290e-05 1.4721581e-02
  9.7560859e-01 9.8641030e-06 2.8073944e-05 1.4649681e-04 9.8950286e-06
  7.5545558e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.52156866 0.5568628  0.5568628 ]
  [0.5058824  0.5411765  0.5411765 ]
  [0.48235294 0.5176471  0.5176471 ]
  ...
  [0.96862745 0.9764706  0.9647059 ]
  [0.96862745 0.9764706  0.9647059 ]
  [0.96862745 0.9764706  0.9647059 ]]

 [[0.52156866 0.5568628  0.5568628 ]
  [0.5058824  0.5411765  0.5411765 ]
  [0.48235294 0.5176471  0.5176471 ]
  ...
  [0.96862745 0.9764706  0.9647059 ]
  [0.96862745 0.9764706  0.9647059 ]
  [0.96862745 0.9764706  0.9647059 ]]

 [[0.52156866 0.5568628  0.5568628 ]
  [0.5058824  0.5411765  0.5411765 ]
  [0.48235294 0.5176471  0.5

1/1 [==============================] - 0s 87ms/step
[[1.7016722e-04 1.5086873e-05 2.3675966e-06 1.5327154e-06 2.3964970e-04
  9.9951851e-01 9.4664176e-07 2.8561419e-06 6.9262051e-06 1.7191006e-06
  4.0220457e-05]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[1.6761300e-03 6.7646048e-05 3.1076619e-05 1.0343819e-05 1.2739894e-02
  9.7881109e-01 8.8018323e-06 2.5733249e-05 1.3137188e-04 8.9147616e-06
  6.4890790e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.89411765 0.9098039  0.91764706]
  [0.89411765 0.9098039  0.91764706]
  [0.89411765 0.9098039  0.91764706]
  ...
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]]

 [[0.89411765 0.9098039  0.91764706]
  [0.89411765 0.9098039  0.91764706]
  [0.89411765 0.9098039  0.91764706]
  ...
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]
  [0.98039216 0.98039216 0.98039216]]

 [[0.89411765 0.9098039  0.91764706]
  [0.89411765 0.9098039  0.91764706]
  [0.89411765 0.9098039  0.9

1/1 [==============================] - 0s 73ms/step
[[1.0592142e-04 2.0369636e-05 9.6752401e-06 9.6970862e-06 1.5722065e-04
  9.9937445e-01 7.5412197e-07 1.1836153e-05 4.1309868e-05 4.0749374e-06
  2.6468094e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[1.48533797e-03 6.10968855e-05 2.78560037e-05 9.80031564e-06
  1.11832637e-02 9.81369138e-01 7.79712173e-06 2.34629661e-05
  1.18164775e-04 8.14786563e-06 5.70610259e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.972549   0.98039216 0.98039216]
  [0.972549   0.98039216 0.98039216]
  [0.972549   0.98039216 0.98039216]
  ...
  [0.8862745  0.91764706 0.94509804]
  [0.9254902  0.92941177 0.9372549 ]
  [0.92941177 0.92156863 0.9137255 ]]

 [[0.972549   0.98039216 0.98039216]
  [0.972549   0.98039216 0.98039216]
  [0.972549   0.98039216 0.98039216]
  ...
  [0.8980392  0.92941177 0.95686275]
  [0.9372549  0.94509804 0.9490196 ]
  [0.9411765  0.93333334 0.9254902 ]]

 [[0.972549   0.98039216 0.98039216]
  [0.972549   0.98039216 0.98039216]
  [0.972549   0.9

1/1 [==============================] - 0s 103ms/step
[[5.3432359e-05 1.8129513e-05 1.8146178e-06 2.2286681e-06 4.3459199e-04
  9.9932718e-01 1.8697432e-06 4.7251278e-06 1.2953378e-05 2.9826001e-06
  1.4007511e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[1.38597295e-03 5.74976257e-05 2.54726510e-05 9.55967971e-06
  9.98714846e-03 9.83275771e-01 7.08825428e-06 2.15044583e-05
  1.14153474e-04 7.70860697e-06 5.10827778e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.95686275 0.9764706  0.9529412 ]
  [0.95686275 0.9764706  0.9529412 ]
  [0.95686275 0.9764706  0.9529412 ]
  ...
  [0.53333336 0.59607846 0.6392157 ]
  [0.53333336 0.59607846 0.6392157 ]
  [0.5254902  0.5882353  0.6313726 ]]

 [[0.95686275 0.9764706  0.9529412 ]
  [0.95686275 0.9764706  0.9529412 ]
  [0.95686275 0.9764706  0.9529412 ]
  ...
  [0.48235294 0.54509807 0.5882353 ]
  [0.47843137 0.5411765  0.5882353 ]
  [0.4745098  0.5372549  0.5803922 ]]

 [[0.95686275 0.9764706  0.9529412 ]
  [0.95686275 0.9764706  0.9529412 ]
  [0.95686275 0.

1/1 [==============================] - 0s 76ms/step
[[1.8724351e-05 4.4223343e-06 1.4659348e-06 1.1882023e-06 6.3563995e-05
  9.9983048e-01 8.2912794e-07 4.6872838e-06 4.6991086e-06 2.0357361e-06
  6.7907298e-05]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[1.24966865e-03 5.24330753e-05 2.30875557e-05 8.73623321e-06
  9.00022779e-03 9.84925687e-01 6.45469254e-06 1.96708279e-05
  1.03321836e-04 7.12010433e-06 4.60385019e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  ...
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  ...
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1. 

1/1 [==============================] - 0s 79ms/step
[[9.4234438e-06 5.8586711e-06 5.0124963e-06 3.0723143e-06 1.1230897e-04
  9.9977547e-01 1.6248551e-06 1.6352527e-05 1.3288375e-05 4.7323988e-06
  5.2879768e-05]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[1.1371765e-03 4.8435832e-05 2.1386224e-05 8.1960306e-06 8.2092313e-03
  9.8625427e-01 6.0446173e-06 1.8987355e-05 9.5138537e-05 6.8305458e-06
  4.1945516e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.9254902  0.9137255  0.92941177]
  [0.9254902  0.9137255  0.92941177]
  [0.9254902  0.9137255  0.92941177]
  ...
  [0.7529412  0.7647059  0.8       ]
  [0.7529412  0.7647059  0.8       ]
  [0.7529412  0.7647059  0.8       ]]

 [[0.9254902  0.9137255  0.92941177]
  [0.9254902  0.9137255  0.92941177]
  [0.9254902  0.9137255  0.92941177]
  ...
  [0.74509805 0.7607843  0.79607844]
  [0.7529412  0.7647059  0.8       ]
  [0.7607843  0.77254903 0.80784315]]

 [[0.9254902  0.9137255  0.92941177]
  [0.9254902  0.9137255  0.92941177]
  [0.9254902  0.9137255  0.9

1/1 [==============================] - 0s 67ms/step
[[6.9012904e-06 1.6025526e-06 6.5607509e-07 5.9870999e-06 2.5013869e-06
  9.9997258e-01 3.0560059e-07 1.8441519e-06 2.3571729e-06 1.0891055e-06
  4.2217930e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[1.0432715e-03 4.4588385e-05 1.9713771e-05 7.9068259e-06 7.5260475e-03
  9.8739326e-01 5.5930200e-06 1.7791552e-05 8.7511798e-05 6.3841621e-06
  3.8481660e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.92941177 0.90588236 0.93333334]
  [0.92941177 0.90588236 0.93333334]
  [0.92941177 0.90588236 0.93333334]
  ...
  [0.6117647  0.6431373  0.6745098 ]
  [0.6431373  0.6745098  0.7019608 ]
  [0.6627451  0.69411767 0.7176471 ]]

 [[0.92941177 0.90588236 0.93333334]
  [0.92941177 0.90588236 0.93333334]
  [0.92941177 0.90588236 0.93333334]
  ...
  [0.6039216  0.63529414 0.6627451 ]
  [0.63529414 0.6666667  0.69411767]
  [0.6509804  0.68235296 0.70980394]]

 [[0.92941177 0.90588236 0.93333334]
  [0.92941177 0.90588236 0.93333334]
  [0.92941177 0.90588236 0.9

1/1 [==============================] - 0s 72ms/step
[[4.8792313e-06 1.7361468e-06 7.6632165e-07 1.0232561e-05 4.0255718e-06
  9.9996686e-01 3.7814775e-07 4.0321879e-06 2.0507341e-06 1.6407970e-06
  3.3930082e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[9.6337876e-04 4.1245679e-05 1.8234688e-05 7.5761113e-06 6.9473572e-03
  9.8836142e-01 5.1854436e-06 1.6578135e-05 8.0959384e-05 5.9721779e-06
  3.5523148e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  ...
  [0.9098039  0.8862745  0.9137255 ]
  [0.9098039  0.8862745  0.9137255 ]
  [0.9098039  0.8862745  0.9137255 ]]

 [[0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  ...
  [0.9098039  0.8862745  0.9137255 ]
  [0.9098039  0.8862745  0.9137255 ]
  [0.9098039  0.8862745  0.9137255 ]]

 [[0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.9

1/1 [==============================] - 0s 67ms/step
[[3.0745398e-06 2.1074570e-06 1.3531117e-06 6.5402321e-07 1.0681351e-05
  9.9995017e-01 3.7442416e-07 4.7624899e-06 2.4710298e-06 1.3617565e-06
  2.2931854e-05]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[8.9491199e-04 3.8664559e-05 1.7126211e-05 7.2975849e-06 6.4522624e-03
  9.8918742e-01 4.8505667e-06 1.6028827e-05 7.5443997e-05 5.6781892e-06
  3.3004044e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  ...
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]
  [0.92941177 0.91764706 0.93333334]]

 [[0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.9

1/1 [==============================] - 0s 67ms/step
[[3.2812407e-06 2.3553180e-06 3.3030483e-06 5.2878640e-06 5.7714460e-06
  9.9992728e-01 5.9741984e-07 1.8380384e-05 6.0104608e-06 3.6435547e-06
  2.3914017e-05]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[8.3551527e-04 3.6264628e-05 1.6087935e-05 7.1021032e-06 6.0225115e-03
  9.8990488e-01 4.5536099e-06 1.5620597e-05 7.0717047e-05 5.4377902e-06
  3.0813143e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.96862745]
  ...
  [0.9607843  1.         0.9882353 ]
  [0.9607843  1.         0.9882353 ]
  [0.9607843  1.         0.9882353 ]]

 [[0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.96862745]
  ...
  [0.9607843  1.         0.9882353 ]
  [0.9607843  1.         0.9882353 ]
  [0.9607843  1.         0.9882353 ]]

 [[0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.9

1/1 [==============================] - 0s 71ms/step
[[3.1899103e-06 3.4488717e-06 1.5422117e-06 2.1048982e-06 2.9008836e-06
  9.9997687e-01 1.6987003e-07 2.3682667e-06 3.5538064e-06 2.0836314e-06
  1.7917954e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[7.8345434e-04 3.4131655e-05 1.5199732e-05 6.9109437e-06 5.6463233e-03
  9.9053347e-01 4.2899310e-06 1.5052172e-05 6.6561588e-05 5.2529435e-06
  2.8893659e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.96862745]
  ...
  [0.9607843  1.         0.9764706 ]
  [0.9607843  1.         0.9764706 ]
  [0.9607843  1.         0.9764706 ]]

 [[0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.96862745]
  ...
  [0.9607843  1.         0.9764706 ]
  [0.9607843  1.         0.9764706 ]
  [0.9607843  1.         0.9764706 ]]

 [[0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.96862745]
  [0.972549   0.99215686 0.9

1/1 [==============================] - 0s 74ms/step
[[1.9463489e-06 1.9374727e-06 6.7271333e-07 5.9290755e-07 2.5147999e-06
  9.9998176e-01 1.2249362e-07 3.0067345e-06 3.0632632e-06 1.0661746e-06
  3.3577849e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[7.37610739e-04 3.23234162e-05 1.44099777e-05 6.63847777e-06
  5.31441206e-03 9.91088688e-01 4.04774983e-06 1.43763145e-05
  6.29210554e-05 5.09217580e-06 2.71959393e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.9490196  0.96862745 0.94509804]
  [0.9490196  0.96862745 0.94509804]
  [0.9490196  0.96862745 0.94509804]
  ...
  [0.9372549  0.9764706  0.9529412 ]
  [0.9372549  0.9764706  0.9529412 ]
  [0.9372549  0.9764706  0.9529412 ]]

 [[0.9490196  0.96862745 0.94509804]
  [0.9490196  0.96862745 0.94509804]
  [0.9490196  0.96862745 0.94509804]
  ...
  [0.9372549  0.9764706  0.9529412 ]
  [0.9372549  0.9764706  0.9529412 ]
  [0.9372549  0.9764706  0.9529412 ]]

 [[0.9490196  0.96862745 0.94509804]
  [0.9490196  0.96862745 0.94509804]
  [0.9490196  0.9

1/1 [==============================] - 0s 77ms/step
[[2.4425399e-06 2.2055358e-06 9.8857754e-07 1.4006197e-06 6.3350681e-06
  9.9996746e-01 2.4695001e-07 4.3047062e-06 5.7440902e-06 1.3490337e-06
  7.4792201e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[6.9719047e-04 3.0932173e-05 1.3714408e-05 6.3615362e-06 5.0200773e-03
  9.9157137e-01 3.8395506e-06 1.4179165e-05 5.9959777e-05 4.8828674e-06
  2.5775419e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.8862745  0.92156863 0.9647059 ]
  [0.8862745  0.92156863 0.9647059 ]
  [0.8862745  0.92156863 0.9647059 ]
  ...
  [0.90588236 0.93333334 0.9882353 ]
  [0.9019608  0.92941177 0.9843137 ]
  [0.90588236 0.93333334 0.9882353 ]]

 [[0.8862745  0.92156863 0.9647059 ]
  [0.8862745  0.92156863 0.9647059 ]
  [0.8862745  0.92156863 0.9647059 ]
  ...
  [0.9137255  0.94509804 0.99607843]
  [0.90588236 0.93333334 0.9882353 ]
  [0.9019608  0.92941177 0.9843137 ]]

 [[0.8862745  0.92156863 0.9647059 ]
  [0.8862745  0.92156863 0.9647059 ]
  [0.8862745  0.92156863 0.9

1/1 [==============================] - 0s 71ms/step
[[4.8626222e-05 1.3893937e-05 5.3051867e-06 4.0478535e-06 7.5804986e-05
  9.9962926e-01 9.2308909e-07 6.0149132e-06 4.7336001e-05 3.2288399e-06
  1.6563979e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[6.61443104e-04 2.96768667e-05 1.31043425e-05 6.10118286e-06
  4.75740293e-03 9.92005110e-01 3.66308564e-06 1.36085782e-05
  5.79715961e-05 4.71017484e-06 2.44724541e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.29803923 0.32941177 0.37254903]
  [0.33333334 0.36078432 0.40784314]
  [0.39215687 0.41960785 0.46666667]
  ...
  [0.8901961  0.9372549  0.99607843]
  [0.8901961  0.94509804 0.99607843]
  [0.89411765 0.9529412  1.        ]]

 [[0.30980393 0.3372549  0.38431373]
  [0.34117648 0.36862746 0.41568628]
  [0.39215687 0.41960785 0.46666667]
  ...
  [0.88235295 0.9372549  0.99607843]
  [0.88235295 0.9372549  0.99215686]
  [0.8862745  0.94509804 1.        ]]

 [[0.30588236 0.3372549  0.38431373]
  [0.3372549  0.3647059  0.4117647 ]
  [0.3882353  0.4

1/1 [==============================] - 0s 79ms/step
[[1.1118600e-06 1.0389036e-06 2.3029496e-07 2.5574877e-07 1.6226061e-06
  9.9998963e-01 1.7365399e-07 9.7641680e-07 2.5954505e-06 9.3473466e-07
  1.4507792e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[6.2904024e-04 2.8341712e-05 1.2470929e-05 5.8193996e-06 4.5198058e-03
  9.9240309e-01 3.4918944e-06 1.2997347e-05 5.5375611e-05 4.5231927e-06
  2.3251313e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.25490198 0.2901961  0.2901961 ]
  [0.25490198 0.2901961  0.2901961 ]
  [0.25490198 0.2901961  0.2901961 ]
  ...
  [0.92156863 0.9254902  1.        ]
  [0.91764706 0.92156863 1.        ]
  [0.9137255  0.91764706 1.        ]]

 [[0.25490198 0.2901961  0.2901961 ]
  [0.25490198 0.2901961  0.2901961 ]
  [0.25490198 0.2901961  0.2901961 ]
  ...
  [0.92156863 0.9254902  1.        ]
  [0.91764706 0.92156863 1.        ]
  [0.9137255  0.91764706 1.        ]]

 [[0.25490198 0.2901961  0.2901961 ]
  [0.25490198 0.2901961  0.2901961 ]
  [0.25490198 0.2901961  0.2

1/1 [==============================] - 0s 67ms/step
[[2.5876166e-06 1.5998958e-06 5.7769307e-07 1.3614446e-06 3.6577790e-06
  9.9997461e-01 3.6150215e-07 2.3596720e-06 8.0115105e-06 1.3217109e-06
  3.6157332e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[5.9922872e-04 2.7078373e-05 1.1901397e-05 5.5852292e-06 4.3047373e-03
  9.9276382e-01 3.3374663e-06 1.2489197e-05 5.2956999e-05 4.3552500e-06
  2.2145954e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.21960784 0.26666668 0.23921569]
  [0.21960784 0.26666668 0.23921569]
  [0.21960784 0.26666668 0.23921569]
  ...
  [0.9098039  0.90588236 0.9647059 ]
  [0.9098039  0.90588236 0.9647059 ]
  [0.9098039  0.90588236 0.9647059 ]]

 [[0.21960784 0.26666668 0.23921569]
  [0.21960784 0.26666668 0.23921569]
  [0.21960784 0.26666668 0.23921569]
  ...
  [0.9098039  0.90588236 0.9647059 ]
  [0.9098039  0.90588236 0.9647059 ]
  [0.9098039  0.90588236 0.9647059 ]]

 [[0.21960784 0.26666668 0.23921569]
  [0.21960784 0.26666668 0.23921569]
  [0.21960784 0.26666668 0.2

1/1 [==============================] - 0s 74ms/step
[[1.5248487e-06 2.0968712e-06 1.4303101e-06 1.7250250e-06 5.0573526e-06
  9.9997079e-01 3.9029777e-07 3.3701151e-06 6.1460896e-06 3.4480813e-06
  4.0219302e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[5.7208538e-04 2.5962448e-05 1.1407257e-05 5.3928288e-06 4.1092625e-03
  9.9309140e-01 3.2038795e-06 1.2079476e-05 5.0858023e-05 4.2482634e-06
  2.1141409e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.26666668 0.31764707 0.27058825]
  [0.26666668 0.31764707 0.27058825]
  [0.26666668 0.31764707 0.27058825]
  ...
  [0.9529412  0.9843137  0.94509804]
  [0.9529412  0.9843137  0.94509804]
  [0.9529412  0.9843137  0.94509804]]

 [[0.26666668 0.31764707 0.27058825]
  [0.26666668 0.31764707 0.27058825]
  [0.26666668 0.31764707 0.27058825]
  ...
  [0.9529412  0.9843137  0.94509804]
  [0.9529412  0.9843137  0.94509804]
  [0.9529412  0.9843137  0.94509804]]

 [[0.26666668 0.31764707 0.27058825]
  [0.26666668 0.31764707 0.27058825]
  [0.26666668 0.31764707 0.2

1/1 [==============================] - 0s 72ms/step
[[4.6880364e-06 3.9984302e-06 8.6965014e-07 2.9330438e-06 5.8450373e-06
  9.9985659e-01 8.8475906e-07 1.2296269e-05 8.0203727e-06 1.9541749e-06
  1.0188537e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[5.4729445e-04 2.4899211e-05 1.0927995e-05 5.2095043e-06 3.9307089e-03
  9.9338990e-01 3.0775595e-06 1.1723819e-05 4.8888014e-05 4.1153789e-06
  2.0231670e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.43529412 0.4627451  0.44313726]
  [0.41960785 0.44705883 0.42745098]
  [0.4        0.42745098 0.40784314]
  ...
  [0.9098039  0.9254902  0.93333334]
  [0.9098039  0.9254902  0.93333334]
  [0.9098039  0.9254902  0.93333334]]

 [[0.42745098 0.45490196 0.43529412]
  [0.41568628 0.4392157  0.42352942]
  [0.39215687 0.41960785 0.4       ]
  ...
  [0.9098039  0.9254902  0.93333334]
  [0.9098039  0.9254902  0.93333334]
  [0.9098039  0.9254902  0.93333334]]

 [[0.4117647  0.4392157  0.41960785]
  [0.4        0.42745098 0.40784314]
  [0.38039216 0.40784314 0.3

1/1 [==============================] - 0s 75ms/step
[[9.8105249e-07 8.5783068e-07 4.8471986e-08 3.2397588e-07 1.0627898e-06
  9.9999011e-01 2.2359205e-07 1.4699054e-06 3.4646621e-06 4.6918001e-07
  1.1229419e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[5.2457472e-04 2.3992021e-05 1.0487386e-05 5.0618719e-06 3.7670664e-03
  9.9366164e-01 2.9808618e-06 1.1584139e-05 4.7133475e-05 4.0248106e-06
  1.9413816e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.8627451  0.88235295 0.85882354]
  [0.8627451  0.88235295 0.85882354]
  [0.8627451  0.88235295 0.85882354]
  ...
  [0.8627451  0.8745098  0.91764706]
  [0.8627451  0.8745098  0.91764706]
  [0.8627451  0.8745098  0.91764706]]

 [[0.8627451  0.88235295 0.85882354]
  [0.8627451  0.88235295 0.85882354]
  [0.8627451  0.88235295 0.85882354]
  ...
  [0.8627451  0.8745098  0.91764706]
  [0.8627451  0.8745098  0.91764706]
  [0.8627451  0.8745098  0.91764706]]

 [[0.8627451  0.88235295 0.85882354]
  [0.8627451  0.88235295 0.85882354]
  [0.8627451  0.88235295 0.8

1/1 [==============================] - 0s 75ms/step
[[9.2297461e-07 2.4904659e-06 2.6420551e-07 8.8650182e-07 4.4246754e-06
  9.9997437e-01 3.2983041e-07 3.7565342e-06 4.0425216e-06 1.3515735e-06
  7.0905508e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[5.0361996e-04 2.3104991e-05 1.0074821e-05 4.8829379e-06 3.6165088e-03
  9.9391448e-01 2.8728480e-06 1.1222929e-05 4.5375291e-05 3.9062161e-06
  1.8639066e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.5411765  0.627451   0.5803922 ]
  [0.5411765  0.627451   0.5803922 ]
  [0.5411765  0.627451   0.5803922 ]
  ...
  [0.8156863  0.88235295 0.84313726]
  [0.8627451  0.92941177 0.8901961 ]
  [0.87058824 0.9372549  0.8980392 ]]

 [[0.5411765  0.627451   0.5803922 ]
  [0.5411765  0.627451   0.5803922 ]
  [0.5411765  0.627451   0.5803922 ]
  ...
  [0.827451   0.89411765 0.85490197]
  [0.8666667  0.93333334 0.89411765]
  [0.87058824 0.9372549  0.8980392 ]]

 [[0.5411765  0.627451   0.5803922 ]
  [0.5411765  0.627451   0.5803922 ]
  [0.5411765  0.627451   0.5

1/1 [==============================] - 0s 70ms/step
[[1.5563621e-06 1.0543253e-06 1.1456205e-07 1.2397293e-06 2.5515196e-06
  9.9998844e-01 9.5341726e-08 9.6502447e-07 1.8249935e-06 7.6065663e-07
  1.4775557e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[4.8431245e-04 2.2284588e-05 9.6963613e-06 4.7421631e-06 3.4775452e-03
  9.9414790e-01 2.7693522e-06 1.0861321e-05 4.3732267e-05 3.8083624e-06
  1.7923143e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.33333334 0.36078432 0.29803923]
  [0.33333334 0.36078432 0.29803923]
  [0.33333334 0.36078432 0.29803923]
  ...
  [0.26666668 0.3019608  0.30980393]
  [0.26666668 0.3019608  0.3019608 ]
  [0.27058825 0.30588236 0.30588236]]

 [[0.33333334 0.36078432 0.29803923]
  [0.33333334 0.36078432 0.29803923]
  [0.33333334 0.36078432 0.29803923]
  ...
  [0.2784314  0.3137255  0.32156864]
  [0.27450982 0.30980393 0.3137255 ]
  [0.2784314  0.3137255  0.3137255 ]]

 [[0.33333334 0.36078432 0.29803923]
  [0.33333334 0.36078432 0.29803923]
  [0.33333334 0.36078432 0.2

1/1 [==============================] - 0s 73ms/step
[[2.3417159e-07 3.1162210e-07 2.6021249e-08 1.0014884e-07 4.6802506e-07
  9.9999738e-01 6.5648031e-08 2.3316589e-07 5.0565438e-07 3.0553474e-07
  2.8054856e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[4.6640993e-04 2.1499469e-05 9.3411336e-06 4.5921047e-06 3.3488118e-03
  9.9436432e-01 2.6699099e-06 1.0484220e-05 4.2161424e-05 3.6870085e-06
  1.7259971e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.5019608  0.54901963 0.47843137]
  [0.5019608  0.54901963 0.47843137]
  [0.50980395 0.5568628  0.4862745 ]
  ...
  [0.22352941 0.2627451  0.2509804 ]
  [0.22352941 0.2627451  0.2509804 ]
  [0.22352941 0.2627451  0.2509804 ]]

 [[0.4862745  0.5294118  0.45882353]
  [0.4862745  0.53333336 0.4627451 ]
  [0.49019608 0.5372549  0.46666667]
  ...
  [0.22352941 0.2627451  0.2509804 ]
  [0.22352941 0.2627451  0.2509804 ]
  [0.22352941 0.2627451  0.2509804 ]]

 [[0.46666667 0.5137255  0.44313726]
  [0.4627451  0.5137255  0.4392157 ]
  [0.4627451  0.50980395 0.4

1/1 [==============================] - 0s 76ms/step
[[7.1649373e-07 5.1359507e-07 8.5072557e-08 4.2625450e-07 2.0776870e-06
  9.9999321e-01 1.2873754e-07 2.9637562e-07 1.0617142e-06 6.9911096e-07
  8.8155622e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[4.4977121e-04 2.0750873e-05 9.0109206e-06 4.4448702e-06 3.2292679e-03
  9.9456549e-01 2.5791585e-06 1.0136440e-05 4.0691033e-05 3.5814251e-06
  1.6644228e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.6666667  0.73333335 0.7019608 ]
  [0.68235296 0.7490196  0.7176471 ]
  [0.69803923 0.7647059  0.73333335]
  ...
  [0.29803923 0.32941177 0.2901961 ]
  [0.2784314  0.30980393 0.27058825]
  [0.26666668 0.29803923 0.25882354]]

 [[0.6313726  0.7019608  0.67058825]
  [0.654902   0.72156864 0.6901961 ]
  [0.6784314  0.74509805 0.7137255 ]
  ...
  [0.29803923 0.32941177 0.2901961 ]
  [0.2784314  0.30980393 0.27058825]
  [0.26666668 0.29803923 0.25882354]]

 [[0.5882353  0.654902   0.62352943]
  [0.6117647  0.6784314  0.64705884]
  [0.63529414 0.7019608  0.6

1/1 [==============================] - 0s 70ms/step
[[1.0306121e-06 5.3167298e-07 1.1588582e-07 1.2143984e-06 1.8657773e-06
  9.9999118e-01 1.9366362e-07 9.3423438e-07 9.0304445e-07 9.4835747e-07
  1.1565943e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[4.3429958e-04 2.0062285e-05 8.7052031e-06 4.3448713e-06 3.1180012e-03
  9.9475235e-01 2.4957112e-06 9.8131277e-06 3.9334995e-05 3.4975246e-06
  1.6070600e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.39215687 0.4392157  0.4117647 ]
  [0.39215687 0.4392157  0.4117647 ]
  [0.39215687 0.4392157  0.4117647 ]
  ...
  [0.2784314  0.29411766 0.30980393]
  [0.2784314  0.29411766 0.30588236]
  [0.2784314  0.29411766 0.3019608 ]]

 [[0.39215687 0.4392157  0.4117647 ]
  [0.39215687 0.4392157  0.4117647 ]
  [0.39215687 0.4392157  0.4117647 ]
  ...
  [0.2784314  0.29411766 0.30980393]
  [0.2784314  0.29411766 0.30588236]
  [0.2784314  0.29411766 0.3019608 ]]

 [[0.39215687 0.4392157  0.4117647 ]
  [0.39215687 0.4392157  0.4117647 ]
  [0.39215687 0.4392157  0.4

1/1 [==============================] - 0s 81ms/step
[[1.9985966e-06 2.0733655e-06 3.5293544e-07 1.3792677e-06 5.4852521e-06
  9.9997199e-01 5.4334612e-07 2.2916952e-06 2.4315552e-06 2.9629909e-06
  8.6020364e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[4.1988259e-04 1.9426876e-05 8.4233916e-06 4.2275419e-06 3.0141885e-03
  9.9492675e-01 2.4212995e-06 9.5229716e-06 3.8076254e-05 3.4301534e-06
  1.5536731e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.31764707 0.3372549  0.3137255 ]
  [0.31764707 0.3372549  0.3137255 ]
  [0.31764707 0.3372549  0.3137255 ]
  ...
  [0.33333334 0.39215687 0.40392157]
  [0.33333334 0.39215687 0.40392157]
  [0.33333334 0.39215687 0.40392157]]

 [[0.31764707 0.3372549  0.3137255 ]
  [0.31764707 0.3372549  0.3137255 ]
  [0.31764707 0.3372549  0.3137255 ]
  ...
  [0.33333334 0.39215687 0.40392157]
  [0.33333334 0.39215687 0.40392157]
  [0.3372549  0.39607844 0.40784314]]

 [[0.31764707 0.3372549  0.3137255 ]
  [0.31764707 0.3372549  0.3137255 ]
  [0.31764707 0.3372549  0.3

1/1 [==============================] - 0s 88ms/step
[[5.8130473e-07 5.0670593e-07 9.5355325e-08 6.4739118e-07 9.7274130e-07
  9.9999189e-01 2.2995137e-07 9.8219823e-07 2.3807117e-06 9.0080960e-07
  7.8638675e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[4.0637946e-04 1.8833860e-05 8.1562494e-06 4.1178014e-06 2.9170476e-03
  9.9508983e-01 2.3571104e-06 9.2658738e-06 3.6926460e-05 3.3767244e-06
  1.5036389e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.5882353  0.59607846 0.65882355]
  [0.6039216  0.6117647  0.6745098 ]
  [0.627451   0.63529414 0.69803923]
  ...
  [0.74509805 0.7490196  0.8235294 ]
  [0.74509805 0.7490196  0.81960785]
  [0.7490196  0.75686276 0.81960785]]

 [[0.61960787 0.627451   0.6901961 ]
  [0.63529414 0.6431373  0.7058824 ]
  [0.654902   0.6666667  0.7294118 ]
  ...
  [0.70980394 0.7137255  0.7882353 ]
  [0.69803923 0.7019608  0.76862746]
  [0.69803923 0.7058824  0.76862746]]

 [[0.65882355 0.6666667  0.7294118 ]
  [0.6745098  0.68235296 0.74509805]
  [0.69803923 0.7058824  0.7

1/1 [==============================] - 0s 78ms/step
[[2.9608148e-06 1.9214606e-06 3.1401882e-07 1.6540153e-05 6.7621359e-06
  9.9995720e-01 4.4011179e-07 1.6483485e-06 6.6380508e-06 2.8132160e-06
  2.7354738e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.9372226e-04 1.8270108e-05 7.9052934e-06 4.1389067e-06 2.8259899e-03
  9.9524271e-01 2.2900208e-06 9.0007425e-06 3.5843019e-05 3.3034478e-06
  1.4567359e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.7764706  0.7882353  0.8235294 ]
  [0.7764706  0.7882353  0.8235294 ]
  [0.7764706  0.7882353  0.8235294 ]
  ...
  [0.36078432 0.4117647  0.34901962]
  [0.36078432 0.4117647  0.34901962]
  [0.36078432 0.4117647  0.34901962]]

 [[0.7764706  0.7882353  0.8235294 ]
  [0.7764706  0.7882353  0.8235294 ]
  [0.7764706  0.7882353  0.8235294 ]
  ...
  [0.36078432 0.4117647  0.34901962]
  [0.36078432 0.4117647  0.34901962]
  [0.36078432 0.4117647  0.34901962]]

 [[0.7764706  0.7882353  0.8235294 ]
  [0.7764706  0.7882353  0.8235294 ]
  [0.7764706  0.7882353  0.8

1/1 [==============================] - 0s 92ms/step
[[9.6873828e-07 6.9983855e-07 1.2337614e-07 2.3921002e-06 2.0561044e-06
  9.9998903e-01 2.2444274e-07 1.0712641e-06 1.6640616e-06 1.4848058e-06
  3.5690979e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.8184831e-04 1.7746426e-05 7.6708930e-06 4.2052443e-06 2.7404469e-03
  9.9538612e-01 2.2270829e-06 8.7638946e-06 3.4831235e-05 3.2596770e-06
  1.4126290e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.72156864 0.77254903 0.8392157 ]
  [0.72156864 0.77254903 0.8392157 ]
  [0.72156864 0.77254903 0.8392157 ]
  ...
  [0.34117648 0.36078432 0.3372549 ]
  [0.34117648 0.36078432 0.3372549 ]
  [0.34117648 0.36078432 0.3372549 ]]

 [[0.72156864 0.77254903 0.8392157 ]
  [0.72156864 0.77254903 0.8392157 ]
  [0.72156864 0.77254903 0.8392157 ]
  ...
  [0.34117648 0.36078432 0.3372549 ]
  [0.34117648 0.36078432 0.3372549 ]
  [0.34117648 0.36078432 0.3372549 ]]

 [[0.72156864 0.77254903 0.8392157 ]
  [0.72156864 0.77254903 0.8392157 ]
  [0.72156864 0.77254903 0.8

1/1 [==============================] - 0s 74ms/step
[[1.4735072e-06 1.7868570e-06 1.2543744e-07 1.6607898e-06 2.4975507e-06
  9.9998641e-01 3.5361708e-07 1.4092521e-06 1.9328104e-06 1.6535405e-06
  6.5116342e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.7068542e-04 1.7251379e-05 7.4477002e-06 4.1270509e-06 2.6599378e-03
  9.9552143e-01 2.1685410e-06 8.5237161e-06 3.3847020e-05 3.1932968e-06
  1.3710912e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.65882355 0.70980394 0.7764706 ]
  [0.65882355 0.70980394 0.7764706 ]
  [0.65882355 0.70980394 0.7764706 ]
  ...
  [0.3254902  0.38431373 0.3372549 ]
  [0.3254902  0.38431373 0.3372549 ]
  [0.3254902  0.38431373 0.3372549 ]]

 [[0.6        0.64705884 0.7176471 ]
  [0.6        0.64705884 0.7176471 ]
  [0.6        0.64705884 0.7176471 ]
  ...
  [0.3254902  0.38431373 0.3372549 ]
  [0.3254902  0.38431373 0.3372549 ]
  [0.3254902  0.38431373 0.3372549 ]]

 [[0.49411765 0.54509807 0.6117647 ]
  [0.49411765 0.54509807 0.6117647 ]
  [0.49411765 0.54509807 0.6

1/1 [==============================] - 0s 91ms/step
[[4.2650041e-07 8.7021516e-07 3.3588123e-08 1.6152840e-06 1.1877145e-06
  9.9999392e-01 1.5358130e-07 1.8851732e-07 4.4778605e-07 6.4267181e-07
  5.8049653e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.6011645e-04 1.6788170e-05 7.2380526e-06 4.0559084e-06 2.5839924e-03
  9.9564904e-01 2.1116125e-06 8.2957858e-06 3.2905282e-05 3.1293064e-06
  1.3319582e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.81960785]
  ...
  [0.3254902  0.35686275 0.31764707]
  [0.3254902  0.35686275 0.31764707]
  [0.3254902  0.35686275 0.31764707]]

 [[0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.81960785]
  ...
  [0.3254902  0.35686275 0.31764707]
  [0.3254902  0.35686275 0.31764707]
  [0.3254902  0.35686275 0.31764707]]

 [[0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.8

1/1 [==============================] - 0s 86ms/step
[[3.1577117e-06 2.6199330e-06 1.9263817e-07 4.1844614e-06 7.8998110e-06
  9.9996543e-01 4.6226921e-07 2.2135682e-06 3.9516594e-06 1.7420305e-06
  8.1905509e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.5015473e-04 1.6360986e-05 7.0390788e-06 3.9851266e-06 2.5123470e-03
  9.9576956e-01 2.0620025e-06 8.0930395e-06 3.2040931e-05 3.0706196e-06
  1.2950684e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.81960785]
  ...
  [0.39607844 0.40784314 0.44313726]
  [0.39607844 0.40784314 0.44313726]
  [0.39607844 0.40784314 0.44313726]]

 [[0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.81960785]
  ...
  [0.39607844 0.40784314 0.44313726]
  [0.39607844 0.40784314 0.44313726]
  [0.39607844 0.40784314 0.44313726]]

 [[0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.81960785]
  [0.7176471  0.8117647  0.8

1/1 [==============================] - 0s 98ms/step
[[1.2970144e-06 5.4653106e-07 4.5918295e-08 6.1360123e-07 1.8317683e-06
  9.9999249e-01 1.1071085e-07 6.7236584e-07 1.0317405e-06 6.5986308e-07
  5.3187046e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.4075766e-04 1.5944752e-05 6.8519594e-06 3.9255901e-06 2.4445341e-03
  9.9588358e-01 2.0131479e-06 7.9112569e-06 3.1222178e-05 3.0315223e-06
  1.2601059e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.89411765]
  ...
  [0.69411767 0.72156864 0.7764706 ]
  [0.6666667  0.69411767 0.7490196 ]
  [0.64705884 0.6745098  0.7294118 ]]

 [[0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.89411765]
  ...
  [0.69411767 0.72156864 0.7764706 ]
  [0.6666667  0.69411767 0.7490196 ]
  [0.64705884 0.6745098  0.7294118 ]]

 [[0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.8

1/1 [==============================] - 0s 72ms/step
[[8.7187209e-06 2.2388967e-06 2.3852496e-07 4.9072046e-06 1.0599816e-05
  9.9996066e-01 1.0604896e-06 1.5701655e-06 2.2552367e-06 5.5440019e-06
  2.2052873e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.3201501e-04 1.5580552e-05 6.6771468e-06 3.8901485e-06 2.3805208e-03
  9.9599093e-01 1.9771410e-06 7.7369314e-06 3.0450199e-05 3.0344554e-06
  1.2270042e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.89411765]
  ...
  [0.827451   0.8392157  0.8745098 ]
  [0.827451   0.8392157  0.8745098 ]
  [0.827451   0.8392157  0.8745098 ]]

 [[0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.89411765]
  ...
  [0.8117647  0.8235294  0.85882354]
  [0.8117647  0.8235294  0.85882354]
  [0.8117647  0.8235294  0.85882354]]

 [[0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.89411765]
  [0.7921569  0.84705883 0.8

1/1 [==============================] - 0s 80ms/step
[[2.1057235e-06 3.0751823e-06 2.2624177e-07 1.4775698e-06 7.9782030e-06
  9.9997985e-01 2.0151107e-07 4.8939444e-07 1.4144683e-06 1.2960941e-06
  1.7806108e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.2358081e-04 1.5235875e-05 6.5134932e-06 3.9322504e-06 2.3197075e-03
  9.9609298e-01 1.9404113e-06 7.5882604e-06 2.9713379e-05 3.0346459e-06
  1.1956178e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.74509805 0.8        0.84705883]
  [0.74509805 0.8        0.84705883]
  [0.74509805 0.8        0.84705883]
  ...
  [0.5058824  0.5372549  0.57254905]
  [0.41960785 0.4509804  0.4745098 ]
  [0.37254903 0.40392157 0.42352942]]

 [[0.74509805 0.8        0.84705883]
  [0.74509805 0.8        0.84705883]
  [0.74509805 0.8        0.84705883]
  ...
  [0.48235294 0.5137255  0.54901963]
  [0.38039216 0.4117647  0.43529412]
  [0.30980393 0.34117648 0.36078432]]

 [[0.74509805 0.8        0.84705883]
  [0.74509805 0.8        0.84705883]
  [0.74509805 0.8        0.8

1/1 [==============================] - 0s 74ms/step
[[1.67766484e-06 5.14083922e-07 1.16368746e-07 1.37658139e-06
  1.40338398e-06 9.99991775e-01 1.89588761e-07 9.33086312e-07
  7.31523642e-07 1.17371678e-06 2.93790691e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.1556969e-04 1.4886257e-05 6.3585326e-06 3.8854241e-06 2.2618966e-03
  9.9618995e-01 1.9008064e-06 7.4517243e-06 2.9006967e-05 3.0015501e-06
  1.1658696e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.75686276 0.8745098  0.9254902 ]
  [0.75686276 0.8745098  0.9254902 ]
  [0.75686276 0.8745098  0.9254902 ]
  ...
  [0.3647059  0.4117647  0.3764706 ]
  [0.3647059  0.4117647  0.3764706 ]
  [0.3647059  0.4117647  0.3764706 ]]

 [[0.75686276 0.8745098  0.9254902 ]
  [0.75686276 0.8745098  0.9254902 ]
  [0.75686276 0.8745098  0.9254902 ]
  ...
  [0.3647059  0.4117647  0.3764706 ]
  [0.3647059  0.4117647  0.3764706 ]
  [0.3647059  0.4117647  0.3764706 ]]

 [[0.75686276 0.8745098  0.9254902 ]
  [0.75686276 0.8745098  0.9254902 ]
  [0.75686276 0.8

1/1 [==============================] - 0s 74ms/step
[[1.3356471e-06 7.5271862e-07 8.5927631e-08 5.7174461e-06 3.0233075e-06
  9.9998069e-01 3.4616886e-07 1.1289725e-06 1.2275912e-06 9.3437609e-07
  4.8855245e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.0791352e-04 1.4539205e-05 6.2070840e-06 3.8629755e-06 2.2068224e-03
  9.9628258e-01 1.8593267e-06 7.3079350e-06 2.8326522e-05 2.9451207e-06
  1.1375040e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.70980394 0.8156863  0.8627451 ]
  [0.70980394 0.8156863  0.8627451 ]
  [0.70980394 0.8156863  0.8627451 ]
  ...
  [0.78039217 0.79607844 0.85490197]
  [0.76862746 0.78431374 0.8352941 ]
  [0.76862746 0.78431374 0.8352941 ]]

 [[0.70980394 0.8156863  0.8627451 ]
  [0.70980394 0.8156863  0.8627451 ]
  [0.70980394 0.8156863  0.8627451 ]
  ...
  [0.78431374 0.8        0.85882354]
  [0.77254903 0.78431374 0.8392157 ]
  [0.77254903 0.7882353  0.8392157 ]]

 [[0.70980394 0.8156863  0.8627451 ]
  [0.70980394 0.8156863  0.8627451 ]
  [0.70980394 0.8156863  0.8

1/1 [==============================] - 0s 88ms/step
[[2.1738219e-06 3.8300183e-07 3.1903934e-08 1.1432089e-06 9.6153599e-07
  9.9999201e-01 2.5658829e-07 3.9100496e-07 1.6979186e-06 4.1797801e-07
  4.7732993e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[3.0065916e-04 1.4203698e-05 6.0608190e-06 3.8053895e-06 2.1543105e-03
  9.9637079e-01 1.8207031e-06 7.1434138e-06 2.7687001e-05 2.8935999e-06
  1.1104293e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.6431373  0.7176471  0.7921569 ]
  [0.6431373  0.7176471  0.7921569 ]
  [0.6431373  0.7176471  0.7921569 ]
  ...
  [0.7647059  0.7921569  0.84705883]
  [0.7647059  0.7921569  0.84705883]
  [0.7647059  0.7921569  0.84705883]]

 [[0.6431373  0.7176471  0.7921569 ]
  [0.6431373  0.7176471  0.7921569 ]
  [0.6431373  0.7176471  0.7921569 ]
  ...
  [0.7647059  0.7921569  0.84705883]
  [0.7647059  0.7921569  0.84705883]
  [0.7647059  0.7921569  0.84705883]]

 [[0.6431373  0.7176471  0.7921569 ]
  [0.6431373  0.7176471  0.7921569 ]
  [0.6431373  0.7176471  0.7

1/1 [==============================] - 0s 102ms/step
[[4.3732853e-06 1.3223992e-06 1.2385840e-07 4.3222112e-06 1.1997140e-06
  9.9998307e-01 5.0287287e-07 8.9289267e-07 1.7696264e-06 1.6039256e-06
  7.7400284e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[2.9377150e-04 1.3903540e-05 5.9227655e-06 3.8389817e-06 2.1042563e-03
  9.9645472e-01 1.7966308e-06 7.0037349e-06 2.7093807e-05 2.8622101e-06
  1.0846419e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.4        0.4509804  0.45490196]
  [0.4        0.4509804  0.4509804 ]
  [0.39215687 0.44313726 0.4392157 ]
  ...
  [0.56078434 0.6        0.64705884]
  [0.5803922  0.6117647  0.67058825]
  [0.59607846 0.61960787 0.6862745 ]]

 [[0.3882353  0.4392157  0.44313726]
  [0.3882353  0.4392157  0.4392157 ]
  [0.38431373 0.43529412 0.43137255]
  ...
  [0.54901963 0.58431375 0.63529414]
  [0.57254905 0.6        0.65882355]
  [0.58431375 0.60784316 0.6745098 ]]

 [[0.39607844 0.44705883 0.43137255]
  [0.39607844 0.44705883 0.43137255]
  [0.39215687 0.4392157  0.

1/1 [==============================] - 0s 97ms/step
[[1.7806508e-06 5.7879993e-07 1.0706170e-07 1.0187379e-06 1.4434432e-06
  9.9999189e-01 1.7762099e-07 3.3694423e-07 1.5414968e-06 9.7752763e-07
  2.3432288e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[2.8713778e-04 1.3601973e-05 5.7946331e-06 3.9526071e-06 2.0564713e-03
  9.9653482e-01 1.7624000e-06 6.8747227e-06 2.6534146e-05 2.8238185e-06
  1.0600403e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.47843137 0.4862745  0.54901963]
  [0.5019608  0.50980395 0.57254905]
  [0.5294118  0.5372549  0.6       ]
  ...
  [0.7764706  0.7921569  0.8509804 ]
  [0.83137256 0.84313726 0.90588236]
  [0.8627451  0.87058824 0.93333334]]

 [[0.47843137 0.4862745  0.54901963]
  [0.5019608  0.50980395 0.57254905]
  [0.5294118  0.5372549  0.6       ]
  ...
  [0.7647059  0.78039217 0.8392157 ]
  [0.8235294  0.83137256 0.89411765]
  [0.8509804  0.85882354 0.92156863]]

 [[0.47843137 0.4862745  0.54901963]
  [0.5019608  0.50980395 0.57254905]
  [0.5294118  0.5372549  0.6

1/1 [==============================] - 0s 124ms/step
[[1.8655439e-06 1.3699849e-06 8.0966863e-08 9.9715680e-07 4.0888535e-06
  9.9998820e-01 1.6986158e-07 3.5997579e-07 1.0889886e-06 1.3851692e-06
  5.3531676e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[2.8079754e-04 1.3316919e-05 5.6675399e-06 3.8828175e-06 2.0108160e-03
  9.9661160e-01 1.7265762e-06 6.7287583e-06 2.5971118e-05 2.7820872e-06
  1.0364901e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.3764706  0.39607844 0.37254903]
  [0.3764706  0.39607844 0.37254903]
  [0.3764706  0.39607844 0.37254903]
  ...
  [0.53333336 0.54509807 0.5803922 ]
  [0.49803922 0.5137255  0.54901963]
  [0.4745098  0.4862745  0.52156866]]

 [[0.3764706  0.39607844 0.37254903]
  [0.3764706  0.39607844 0.37254903]
  [0.3764706  0.39607844 0.37254903]
  ...
  [0.53333336 0.54509807 0.5803922 ]
  [0.49803922 0.5058824  0.54509807]
  [0.4862745  0.49803922 0.53333336]]

 [[0.3764706  0.39607844 0.37254903]
  [0.3764706  0.39607844 0.37254903]
  [0.3764706  0.39607844 0.

1/1 [==============================] - 0s 73ms/step
[[1.7167021e-06 7.3529827e-07 1.4983176e-07 1.2567120e-05 3.1470488e-06
  9.9997139e-01 3.1888874e-07 7.3458614e-07 1.4981455e-06 2.4051330e-06
  5.2693549e-06]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[2.7472700e-04 1.3054943e-05 5.5461182e-06 3.9415922e-06 1.9671614e-03
  9.9668479e-01 1.6958594e-06 6.5922763e-06 2.5435407e-05 2.7680830e-06
  1.0140014e-03]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.70980394 0.7607843  0.827451  ]
  [0.6784314  0.73333335 0.8       ]
  [0.627451   0.6784314  0.74509805]
  ...
  [0.5686275  0.5882353  0.6901961 ]
  [0.5176471  0.5372549  0.6392157 ]
  [0.4862745  0.50980395 0.6117647 ]]

 [[0.70980394 0.7607843  0.827451  ]
  [0.68235296 0.7294118  0.8       ]
  [0.627451   0.6784314  0.74509805]
  ...
  [0.5686275  0.5882353  0.6901961 ]
  [0.5176471  0.5372549  0.6392157 ]
  [0.4862745  0.5058824  0.6117647 ]]

 [[0.70980394 0.7607843  0.827451  ]
  [0.6784314  0.7294118  0.8       ]
  [0.627451   0.6784314  0.7

1/1 [==============================] - 0s 109ms/step
[[3.8914245e-06 1.2020654e-06 5.8066991e-08 4.2074607e-06 1.9827858e-06
  9.9998319e-01 4.0557268e-07 4.9748849e-07 1.4399233e-06 2.9849252e-06
  1.9996035e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[2.68992648e-04 1.28029715e-05 5.42974294e-06 3.93391838e-06
  1.92535599e-03 9.96755004e-01 1.67088524e-06 6.46282979e-06
  2.49283858e-05 2.76391870e-06 9.92439920e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[[0.7294118  0.7529412  0.827451  ]
  [0.7294118  0.7529412  0.827451  ]
  [0.7294118  0.7529412  0.827451  ]
  ...
  [0.6627451  0.6745098  0.7529412 ]
  [0.6627451  0.6745098  0.75686276]
  [0.6627451  0.6745098  0.7607843 ]]

 [[0.7294118  0.7529412  0.827451  ]
  [0.7294118  0.7529412  0.827451  ]
  [0.7294118  0.7529412  0.827451  ]
  ...
  [0.6627451  0.6745098  0.7529412 ]
  [0.6627451  0.6745098  0.75686276]
  [0.6627451  0.6745098  0.7607843 ]]

 [[0.7294118  0.7529412  0.827451  ]
  [0.7294118  0.7529412  0.827451  ]
  [0.7294118  0.

1/1 [==============================] - 0s 83ms/step
[[4.4320404e-06 2.4280694e-06 1.0684451e-07 5.8828273e-06 2.0235898e-06
  9.9998105e-01 2.8922616e-07 5.8102904e-07 1.0623069e-06 1.6057772e-06
  6.3857448e-07]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
[[2.6366301e-04 1.2577010e-05 5.3194499e-06 3.9462593e-06 1.8852997e-03
  9.9682206e-01 1.6430772e-06 6.3444754e-06 2.4448185e-05 2.7485105e-06
  9.7177963e-04]]
✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
